language: minimal

services:
  - docker

script:
  - docker --version
  #- docker-compose -f docker-compose-build.yaml build
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-user chimezdev/udagram-api-user:latest
  - docker tag udagram-api-feed chimezdev/udagram-api-feed:latest
  - docker tag udagram-frontend chimezdev/udagram-frontend:latest
  - docker tag udagram-reverseproxy chimezdev/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chimezdev/udagram-api-user:latest
  - docker push chimezdev/udagram-api-feed:latest
  - docker push chimezdev/udagram-frontend:latest
  - docker push chimezdev/udagram-reverseproxy:latest

  # deploy:
  # provider: script
  # script: bash docker-push.sh
  # on:
  #   branch: main