language: minimal

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t chimezdev/udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-user chimezdev/udagram-api-user:v4
  - docker tag udagram-api-feed chimezdev/udagram-api-feed:v4
  - docker tag udagram-frontend chimezdev/udagram-frontend:v4
  - docker tag udagram-reverseproxy chimezdev/udagram-reverseproxy:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chimezdev/udagram-api-user:v4
  - docker push chimezdev/udagram-api-feed:v4
  - docker push chimezdev/udagram-frontend:v4
  - docker push chimezdev/udagram-reverseproxy:v4
