language: minimal

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yml build

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master